"""Incident state machine."""
from __future__ import annotations

OPEN = "OPEN"
INVESTIGATING = "INVESTIGATING"
MITIGATING = "MITIGATING"
MONITORING = "MONITORING"
RESOLVED = "RESOLVED"
ESCALATED = "ESCALATED"
FALSE_POSITIVE = "FALSE_POSITIVE"

TERMINAL = {RESOLVED, ESCALATED, FALSE_POSITIVE}

VALID_TRANSITIONS: dict[str, set[str]] = {
    OPEN: {INVESTIGATING, MONITORING, RESOLVED, ESCALATED, FALSE_POSITIVE},
    INVESTIGATING: {MITIGATING, MONITORING, RESOLVED, ESCALATED, FALSE_POSITIVE},
    MITIGATING: {MONITORING, RESOLVED, ESCALATED, FALSE_POSITIVE},
    MONITORING: {MITIGATING, RESOLVED, ESCALATED, FALSE_POSITIVE},
    RESOLVED: set(),
    ESCALATED: set(),
    FALSE_POSITIVE: set(),
}


def can_transition(current: str, target: str) -> bool:
    return target in VALID_TRANSITIONS.get(current, set())
