"""Generate a compact land-only particle source file for the globe.

Samples a jittered lat/lon grid, keeps points inside Natural Earth 110m land
polygons (ray-casting, holes respected), and writes a TypeScript module with a
flat [lat, lon, ...] array the globe converts to spherical coordinates.

Usage:
    python tools/generate_landmask.py <input.geojson> <output.ts> [max_points]
"""
from __future__ import annotations

import json
import random
import sys


def point_in_ring(lon: float, lat: float, ring: list[list[float]]) -> bool:
    """Standard ray-casting against one linear ring of [lon, lat] pairs."""
    inside = False
    j = len(ring) - 1
    for i in range(len(ring)):
        xi, yi = ring[i][0], ring[i][1]
        xj, yj = ring[j][0], ring[j][1]
        if (yi > lat) != (yj > lat):
            x_cross = (xj - xi) * (lat - yi) / (yj - yi) + xi
            if lon < x_cross:
                inside = not inside
        j = i
    return inside


def in_polygon(lon: float, lat: float, polygon: list) -> bool:
    if not polygon:
        return False
    if not point_in_ring(lon, lat, polygon[0]):      # exterior
        return False
    for hole in polygon[1:]:                          # holes exclude
        if point_in_ring(lon, lat, hole):
            return False
    return True


def in_land(lon: float, lat: float, polygons: list) -> bool:
    return any(in_polygon(lon, lat, p) for p in polygons)


def main() -> None:
    src, out = sys.argv[1], sys.argv[2]
    max_points = int(sys.argv[3]) if len(sys.argv) > 3 else 30000

    with open(src, encoding="utf-8") as fh:
        geo = json.load(fh)

    polygons: list = []
    for feature in geo["features"]:
        geom = feature["geometry"]
        if geom["type"] == "Polygon":
            polygons.append(geom["coordinates"])
        elif geom["type"] == "MultiPolygon":
            polygons.extend(geom["coordinates"])

    rng = random.Random(42)
    candidates: list[tuple[float, float]] = []
    step = 0.6
    lat = -90.0 + step / 2
    while lat < 90.0:
        lon = -180.0 + step / 2
        # cos(lat) weighting keeps area density roughly uniform on the sphere
        while lon < 180.0:
            jlat = lat + rng.uniform(-0.28, 0.28)
            jlon = lon + rng.uniform(-0.28, 0.28)
            if in_land(jlon, jlat, polygons):
                candidates.append((round(jlat, 2), round(jlon, 2)))
            lon += step
        lat += step

    rng.shuffle(candidates)
    chosen = candidates[:max_points]
    flat = ", ".join(f"{la},{lo}" for la, lo in chosen)

    with open(out, "w", encoding="utf-8") as fh:
        fh.write(
            "// AUTO-GENERATED by tools/generate_landmask.py from Natural Earth 110m land.\n"
            "// Flat [lat, lon, ...] degrees. Do not edit by hand.\n"
            f"export const LAND_POINT_COUNT = {len(chosen)};\n"
            f"export const LAND_POINTS: number[] = [{flat}];\n"
        )
    print(f"polygons={len(polygons)} candidates={len(candidates)} written={len(chosen)} -> {out}")


if __name__ == "__main__":
    main()
